### ISSUE TITLE
FTM-100DR protocol

### ISSUE THREAD

**Issue by Jacky-Chiang** [tomelec/ft-857_front_panel_protocol#1]
Can you help me analyze the FTM-100DR protocol between TRX and PAN?

**Comment by haxwithaxe** [comment]
Sorry. I'm still unpacking from a move. I'll get my stuff setup in the next week or two.

On June 20, 2019 2:26:37 AM EDT, Jacky-Chiang <notifications@github.com> wrote:
>Can you help me analyze the FTM-100DR protocol between TRX and PAN?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tomelec** [comment]
Difficult since I do not have access to that radio.
I suggest you use the same approach as I did with the FT-857D. Maybe the protocols are related to each other? Who knows.
